### ISSUE TITLE
NDX-DN11: fix event debug info specification

### ISSUE THREAD

**Issue by AnnaShaleva** [ngdseattle/design-notes#8]
**Describe the bug**
[NDX-DN11](https://github.com/ngdseattle/design-notes/blob/master/NDX-DN11%20-%20NEO%20Debug%20Info%20Specification.md#v11-format) suppose that event name should have the format `{namespace}-{display-name}`. However, neon3 compiler generates event name in `{namespace},{display-name}` (comma-separated) format. And neo3 debugger also expects the same comma-separated name format and throws an error otherwise.

**Expected behaviour**
Event name standard should match implementation.

**Comment by devhawk** [comment]
Thanks @AnnaShaleva. this is a mistake in the spec. WIll fix
